import { Command } from "commander";
import chalk from "chalk";
import { existsSync, writeFileSync } from "fs";
import { resolve } from "path";
import { loadConfig } from "../config.ts";
import { isSteamCmdInstalled, isServerInstalled } from "../services/checks.ts";
import { isServerRunning } from "../services/server.ts";

function makeDefaultConfig(dir: string): string {
  return `# Conan Exiles dedicated server configuration
# Generated by: conan init
#
# Required fields are uncommented. Optional fields show their defaults — uncomment to override.

server:
  # Absolute path where the server is (or will be) installed
  dir: ${dir}
  # Linux user account that owns and runs the server process
  # user: steam
  # Path or command name for SteamCMD — defaults to "steamcmd" (must be on PATH)
  # steamcmd: steamcmd
  # Steam App ID for the Conan Exiles dedicated server
  # steam_app_id: "443030"
  # Server launch script filename, relative to server.dir
  # binary: ConanSandboxServer.sh

tmux:
  # Name of the tmux session used to run the server
  # session: conan

params:
  # Server display name shown in the in-game server browser
  # name: "Conan Exiles Server"
  # Map to load: ConanSandbox (Exiled Lands) or DLC_Isle_of_Siptah (Isle of Siptah)
  # map: ConanSandbox
  # Maximum number of concurrent players
  # max_players: 40
  # Game port (UDP) — must be open in your firewall
  # port: 7777
  # Steam query port (UDP) — used for server browser discovery
  # query_port: 27015
  # RCON port (TCP) — for remote console access
  # rcon_port: 25575
  # Enable the RCON remote console interface
  # rcon_enabled: true
  # Password required to join the server (leave commented for a public server)
  # password: ""
  # Admin password for in-game admin access
  # admin_password: ""

backups:
  # Number of rolling save backups to keep before pruning old ones
  # keep: 5
  # Directory where save backups are stored (default: <server.dir>/backups)
  # dir: ${dir}/backups

mods:
  # Steam Workshop App ID for Conan Exiles mods
  # app_id: "440900"
  # List of Workshop mods to install and load, applied in order
  # list:
  #   - id: "123456789"
  #     # Human-readable label for your reference — not used by the server
  #     # name: Example Mod
`;
}

export function registerInit(program: Command): void {
  program
    .command("init")
    .description("Create a minimal config.yaml with sane defaults")
    .option("-f, --force", "Overwrite an existing config file")
    .action(async (opts) => {
      const cwd = process.cwd();
      const outPath = resolve(cwd, program.opts().config ?? "config.yaml");

      if (existsSync(outPath) && !opts.force) {
        throw new Error(`Config already exists: ${outPath}\nUse --force to overwrite.`);
      }

      writeFileSync(outPath, makeDefaultConfig(cwd), "utf-8");
      console.log(chalk.green(`Created: ${outPath}`));
      console.log(`  server.dir set to: ${cwd}`);
      console.log("");

      const config = loadConfig(outPath);
      const [steamCmdOk, serverOk, runningOk] = await Promise.all([
        isSteamCmdInstalled(config.server.steamcmd),
        isServerInstalled(config.server.dir, config.server.binary),
        isServerRunning(config.tmux.session),
      ]);

      const box = (done: boolean) => (done ? chalk.green("[✓]") : "[ ]");

      console.log("Next steps:");
      console.log(`  ${box(steamCmdOk)} 1. Install SteamCMD: https://developer.valvesoftware.com/wiki/SteamCMD`);
      console.log(`  ${box(serverOk)} 2. Run \`conan install\` to download the server`);
      console.log(`  ${box(runningOk)} 3. Run \`conan start\` to launch`);
    });
}
