import { defineCommand, option } from "@bunli/core";
import { existsSync, writeFileSync } from "fs";
import { resolve } from "path";
import { z } from "zod";

function makeDefaultConfig(dir: string): string {
  return `# Conan Exiles dedicated server configuration
# Generated by: conan init
#
# Required fields are uncommented. Optional fields show their defaults — uncomment to override.

server:
  # Absolute path where the server is (or will be) installed
  dir: ${dir}
  # Linux user account that owns and runs the server process
  # user: steam
  # Path or command name for SteamCMD — defaults to "steamcmd" (must be on PATH)
  # steamcmd: steamcmd
  # Steam App ID for the Conan Exiles dedicated server
  # steam_app_id: "443030"
  # Server launch script filename, relative to server.dir
  # binary: ConanSandboxServer.sh

tmux:
  # Name of the tmux session used to run the server
  # session: conan

params:
  # Server display name shown in the in-game server browser
  # name: "Conan Exiles Server"
  # Map to load: ConanSandbox (Exiled Lands) or DLC_Isle_of_Siptah (Isle of Siptah)
  # map: ConanSandbox
  # Maximum number of concurrent players
  # max_players: 40
  # Game port (UDP) — must be open in your firewall
  # port: 7777
  # Steam query port (UDP) — used for server browser discovery
  # query_port: 27015
  # RCON port (TCP) — for remote console access
  # rcon_port: 25575
  # Enable the RCON remote console interface
  # rcon_enabled: true

backups:
  # Number of rolling save backups to keep before pruning old ones
  # keep: 5
  # Directory where save backups are stored (default: <server.dir>/backups)
  # dir: ${dir}/backups

mods:
  # Steam Workshop App ID for Conan Exiles mods
  # app_id: "440900"
  # List of Workshop mods to install and load, applied in order
  # list:
  #   - id: "123456789"
  #     # Human-readable label for your reference — not used by the server
  #     # name: Example Mod
`;
}

export default defineCommand({
  name: "init",
  description: "Create a minimal config.yaml with sane defaults",
  options: {
    config: option(z.string().optional(), {
      description: "Output path for the config file (default: ./config.yaml)",
      short: "c",
    }),
    force: option(z.boolean().default(false), {
      description: "Overwrite an existing config file",
      short: "f",
    }),
  },
  handler: async ({ flags, colors }) => {
    const cwd = process.cwd();
    const outPath = resolve(cwd, flags.config ?? "config.yaml");

    if (existsSync(outPath) && !flags.force) {
      console.error(colors.yellow(`Config already exists: ${outPath}`));
      console.error(`Use --force to overwrite.`);
      process.exit(1);
    }

    writeFileSync(outPath, makeDefaultConfig(cwd), "utf-8");
    console.log(colors.green(`Created: ${outPath}`));
    console.log(`  server.dir set to: ${cwd}`);
    console.log("");
    console.log("Next steps:");
    console.log(`  1. Install SteamCMD: https://developer.valvesoftware.com/wiki/SteamCMD`);
    console.log(`  2. Run \`conan install\` to download the server`);
    console.log(`  3. Run \`conan start\` to launch`);
  },
});
